name: Build and Format Check

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Build
      run: dotnet build -c Release

  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Install global tools
      run: |
        dotnet tool restore
        dotnet tool install -g dotnet-format --version 3.3.0

    - name: Check code formatting
      run: dotnet format --check --verbosity diagnostic
